<h2><i class="fa fa-homr"></i>Accueil</h2>
<ul>

<?php for($i = 0; $i < count($posts); $i++ ): ?>

<li class="post">
  <h3>
    <i></i>
  </h3>
    <p><?= htmlspecialchars($posts[$i]["Contents"] ) ?></p>
    <a href="show-post.php?id=<?= htmlspecialchars($posts[$i]['Id']) ?>"><?= htmlspecialchars($posts[$i]['Title'])?></a>
    <p>Rédigé par <?= htmlspecialchars($posts[$i]["FirstName"]) ?> <?= htmlspecialchars($posts[$i]["LastName"]) ?> le <?= htmlspecialchars($posts[$i]["CreationTimestamp"]) ?></p>
  
</li>
+
<?php endfor; ?>
</ul>